### ISSUE TITLE
About upload bigger files (more than 5GB)

### ISSUE THREAD

**Issue by hikarus211** [maxbeatty/aws-s3-browser-upload-example#3]
I have a question about upload over 5GB files, like video files.
Right now it can only upload image file not over 100MB. Should I just delete `['content-length-range', 1, 1024 * 1024 * 100], // 100 MB limit`? Do I need to add "Multipart"?

**Comment by maxbeatty** [comment]
Yes, you'll need to adjust or remove that. You'll definitely need multipart and maybe a different endpoint altogether for a file that big.
